export const CATEGORIES = ['DigiCert & Thawte', 'RapidSSL & GeoTrust', 'VMC / CMC', 'Automation']

export const PRODUCTS = [
  // DigiCert & Thawte
  {
    id: 'dc-secure-site-pro-ov',
    ca: 'DigiCert',
    category: 'DigiCert & Thawte',
    name: 'Secure Site Pro OV',
    type: 'Organization Validated · Single domain',
    featured: true,
    badge: 'Most trusted',
    features: [
      { check: true, text: 'Organization validated (OV)' },
      { check: true, text: '$1.75M warranty' },
      { check: true, text: 'RSA 2048 / ECC P-256' },
      { check: true, text: 'Priority 24h validation' },
      { check: true, text: 'Post-quantum ready' },
      { check: false, text: 'No wildcard' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'dc-secure-site-ev',
    ca: 'DigiCert',
    category: 'DigiCert & Thawte',
    name: 'Secure Site EV',
    type: 'Extended Validation · Single domain',
    features: [
      { check: true, text: 'Extended validation (EV)' },
      { check: true, text: '$1.5M warranty' },
      { check: true, text: 'Highest trust indicator' },
      { check: true, text: 'Multi-domain via SANs' },
      { check: true, text: 'Malware scan included' },
      { check: false, text: 'No wildcard' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'dc-wildcard-ov',
    ca: 'DigiCert',
    category: 'DigiCert & Thawte',
    name: 'Secure Site Wildcard OV',
    type: 'Organization Validated · Wildcard',
    features: [
      { check: true, text: 'Wildcard (*.domain.com)' },
      { check: true, text: '$1.25M warranty' },
      { check: true, text: 'Unlimited subdomains' },
      { check: true, text: 'OV validation' },
      { check: false, text: 'Single root domain only' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'thawte-ssl-web-ov',
    ca: 'Thawte',
    category: 'DigiCert & Thawte',
    name: 'SSL Web Server OV',
    type: 'Organization Validated · Single domain',
    features: [
      { check: true, text: 'Organization validated' },
      { check: true, text: '$1.25M warranty' },
      { check: true, text: 'SAN support' },
      { check: true, text: 'Global recognition' },
      { check: false, text: 'No EV indicator' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'thawte-ssl-web-ev',
    ca: 'Thawte',
    category: 'DigiCert & Thawte',
    name: 'SSL Web Server EV',
    type: 'Extended Validation · Single domain',
    features: [
      { check: true, text: 'EV validation' },
      { check: true, text: '$1.5M warranty' },
      { check: true, text: 'Increased user trust' },
      { check: true, text: 'Green bar indicator' },
      { check: false, text: 'No wildcard' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'thawte-wildcard',
    ca: 'Thawte',
    category: 'DigiCert & Thawte',
    name: 'Wildcard SSL',
    type: 'Domain Validated · Wildcard',
    features: [
      { check: true, text: 'Wildcard coverage' },
      { check: true, text: '$1M warranty' },
      { check: true, text: 'Quick DV issuance' },
      { check: false, text: 'No EV or OV' },
    ],
    price: 'Contact for pricing',
  },

  // RapidSSL & GeoTrust
  {
    id: 'rapidssl-dv',
    ca: 'RapidSSL',
    category: 'RapidSSL & GeoTrust',
    name: 'RapidSSL Standard',
    type: 'Domain Validated · Single domain',
    features: [
      { check: true, text: 'Domain validated (DV)' },
      { check: true, text: '$10K warranty' },
      { check: true, text: 'Minutes issuance' },
      { check: true, text: '2048-bit RSA' },
      { check: false, text: 'No OV/EV' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'rapidssl-wildcard',
    ca: 'RapidSSL',
    category: 'RapidSSL & GeoTrust',
    name: 'RapidSSL Wildcard',
    type: 'Domain Validated · Wildcard',
    features: [
      { check: true, text: 'Wildcard (*.domain.com)' },
      { check: true, text: '$10K warranty' },
      { check: true, text: 'Fast DV issuance' },
      { check: true, text: 'Unlimited subdomains' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'geotrust-ov',
    ca: 'GeoTrust',
    category: 'RapidSSL & GeoTrust',
    name: 'True BusinessID OV',
    type: 'Organization Validated · Single domain',
    features: [
      { check: true, text: 'Organization validated' },
      { check: true, text: '$1.25M warranty' },
      { check: true, text: 'SAN support' },
      { check: true, text: 'Dynamic site seal' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'geotrust-ev',
    ca: 'GeoTrust',
    category: 'RapidSSL & GeoTrust',
    name: 'True BusinessID EV',
    type: 'Extended Validation · Single domain',
    featured: true,
    badge: 'Popular',
    features: [
      { check: true, text: 'EV validation' },
      { check: true, text: '$1.5M warranty' },
      { check: true, text: 'Highest trust level' },
      { check: true, text: 'Company name visible' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'geotrust-wildcard',
    ca: 'GeoTrust',
    category: 'RapidSSL & GeoTrust',
    name: 'True BusinessID Wildcard',
    type: 'Organization Validated · Wildcard',
    features: [
      { check: true, text: 'Wildcard OV' },
      { check: true, text: '$1.25M warranty' },
      { check: true, text: 'Unlimited subdomains' },
      { check: true, text: 'Dynamic site seal' },
    ],
    price: 'Contact for pricing',
  },

  // VMC / CMC
  {
    id: 'digicert-vmc',
    ca: 'DigiCert',
    category: 'VMC / CMC',
    name: 'Verified Mark Certificate',
    type: 'VMC · Brand Logo in Email',
    featured: true,
    badge: 'BIMI enabled',
    features: [
      { check: true, text: 'Brand logo in Gmail / Apple Mail' },
      { check: true, text: 'BIMI standard compliant' },
      { check: true, text: 'Trademark verification' },
      { check: true, text: 'Enhanced email trust' },
      { check: true, text: 'Reduces phishing risk' },
    ],
    price: 'Contact for pricing',
  },
  {
    id: 'digicert-cmc',
    ca: 'DigiCert',
    category: 'VMC / CMC',
    name: 'Common Mark Certificate',
    type: 'CMC · Unregistered mark',
    features: [
      { check: true, text: 'Logo without trademark req.' },
      { check: true, text: 'BIMI compatible' },
      { check: true, text: 'Email brand visibility' },
      { check: false, text: 'No trademark verification' },
    ],
    price: 'Contact for pricing',
  },

  // Automation products (GoGetSSL v2)
  {
    id: 'rapidssl-automate',
    ca: 'RapidSSL',
    category: 'Automation',
    name: 'RapidSSL DV + Automate',
    type: 'DV · Single domain · Auto-renew',
    featured: true,
    badge: 'Expert pick',
    gogetssl_id: 400,
    features: [
      { check: true, text: 'Fully automated renewal' },
      { check: true, text: 'Agent or ACME install' },
      { check: true, text: 'Any server type' },
      { check: true, text: 'AutoInstall dashboard' },
      { check: false, text: 'No wildcard' },
    ],
    price: '$63 / year',
  },
  {
    id: 'rapidssl-wildcard-automate',
    ca: 'RapidSSL',
    category: 'Automation',
    name: 'RapidSSL Wildcard + Automate',
    type: 'DV · Wildcard · Auto-renew',
    gogetssl_id: 401,
    badge: 'Linux admin favourite',
    features: [
      { check: true, text: '*.domain.com coverage' },
      { check: true, text: 'Fully automated renewal' },
      { check: true, text: 'Agent or ACME install' },
      { check: true, text: 'Any server type' },
    ],
    price: '$236 / year',
  },
  {
    id: 'geotrust-automate',
    ca: 'GeoTrust',
    category: 'Automation',
    name: 'GeoTrust DV + Automate',
    type: 'DV · Single domain · Auto-renew',
    gogetssl_id: 402,
    badge: 'Top pick',
    features: [
      { check: true, text: 'GeoTrust brand trust' },
      { check: true, text: 'Fully automated renewal' },
      { check: true, text: 'Agent or ACME install' },
      { check: true, text: 'Any server type' },
    ],
    price: '$168 / year',
  },
  {
    id: 'geotrust-wildcard-automate',
    ca: 'GeoTrust',
    category: 'Automation',
    name: 'GeoTrust Wildcard + Automate',
    type: 'DV · Wildcard · Auto-renew',
    gogetssl_id: 403,
    badge: 'Best for teams',
    features: [
      { check: true, text: 'Wildcard + automation' },
      { check: true, text: 'Fully automated renewal' },
      { check: true, text: 'Agent or ACME install' },
      { check: true, text: 'Any server type' },
    ],
    price: '$708 / year',
  },
  {
    id: 'sectigo-caas',
    ca: 'Sectigo',
    category: 'Automation',
    name: 'Sectigo ACME CaaS',
    type: 'ACME · Certificate-as-a-Service',
    gogetssl_id: 300,
    features: [
      { check: true, text: 'Unlimited domains' },
      { check: true, text: 'ACME protocol only' },
      { check: true, text: 'Per-domain pricing' },
      { check: false, text: 'No agent install' },
    ],
    price: '$79 / domain / year',
  },
  {
    id: 'positivessl-caas',
    ca: 'Sectigo',
    category: 'Automation',
    name: 'PositiveSSL CaaS',
    type: 'ACME · Certificate-as-a-Service',
    features: [
      { check: true, text: 'Entry-level ACME CaaS' },
      { check: true, text: 'Unlimited domains' },
      { check: true, text: 'ACME protocol' },
      { check: false, text: 'No agent install' },
    ],
    price: '$39 / domain / year',
  },
]
