// Complete GoGetSSL product ID → name map
// Generated from /api/products/ssl — covers all 78 products
export const PRODUCT_MAP = {
  12:"GeoTrust QuickSSL Premium SAN",
  24:"Thawte SSL Web Server Multi-Domain Wildcard",
  25:"GeoTrust TrueBusinessID SAN Wildcard",
  26:"GeoTrust QuickSSL Premium",
  27:"GeoTrust TrueBusinessID",
  28:"GeoTrust TrueBusinessID Wildcard",
  29:"GeoTrust TrueBusinessID EV",
  30:"GeoTrust TrueBusinessID SAN",
  31:"RapidSSL Standard",
  32:"RapidSSL WildcardSSL",
  35:"Thawte Web Server SSL",
  36:"Thawte SSL 123",
  37:"Thawte Web Server EV",
  38:"Thawte Wildcard SSL Certificate",
  39:"DigiCert Code Signing SSL",
  41:"DigiCert Secure Site",
  42:"DigiCert Secure Site PRO",
  43:"DigiCert Secure Site PRO EV",
  44:"DigiCert Secure Site EV",
  45:"Sectigo PositiveSSL",
  46:"Sectigo PositiveSSL Wildcard",
  47:"Sectigo InstantSSL",
  48:"Sectigo InstantSSL Pro",
  49:"Sectigo InstantSSL Premium",
  50:"Sectigo InstantSSL Premium Wildcard",
  53:"Sectigo SSL UCC OV",
  54:"Sectigo Multi-Domain SSL",
  55:"Sectigo EV SSL",
  57:"Sectigo Multi-Domain EV SSL",
  63:"Sectigo PositiveSSL Multi-Domain Wildcard (3 SAN)",
  65:"GoGetSSL 90-day Trial SSL",
  66:"GoGetSSL Domain SSL",
  67:"GoGetSSL Wildcard SSL",
  68:"GoGetSSL Multi-Domain SSL",
  71:"GeoTrust TrueBusinessID EV SAN",
  75:"Sectigo Essential SSL",
  76:"Sectigo Essential Wildcard SSL",
  77:"Sectigo PositiveSSL Multi-Domain",
  82:"Sectigo SSL Certificate",
  84:"DigiCert Secure Site Wildcard",
  85:"Sectigo SSL UCC DV",
  86:"Sectigo Intel vPro AMT",
  89:"DigiCert EV Code Signing Certificate",
  99:"Sectigo PositiveSSL Multi-Domain Wildcard",
  100:"Sectigo Multi-Domain Wildcard SSL",
  105:"Sectigo SSL Wildcard",
  111:"Thawte SSL 123 Wildcard",
  112:"GeoTrust QuickSSL Premium Wildcard",
  113:"DigiCert Secure Site PRO Wildcard",
  118:"Sectigo PositiveSSL EV",
  119:"Sectigo PositiveSSL EV MDC",
  120:"Sectigo UCC DV Wildcard SSL",
  125:"Sectigo EnterpriseSSL",
  126:"Sectigo EnterpriseSSL Pro",
  127:"Sectigo EnterpriseSSL Pro Wildcard",
  128:"Sectigo UCC OV Wildcard SSL",
  129:"Sectigo EnterpriseSSL Pro EV",
  130:"Sectigo EnterpriseSSL Pro EV MDC",
  131:"Sectigo EV Code Signing SSL",
  132:"GoGetSSL BusinessTrust EV",
  133:"GoGetSSL BusinessTrust EV SAN",
  134:"GoGetSSL BusinessTrust",
  135:"GoGetSSL BusinessTrust Wildcard",
  136:"GoGetSSL BusinessTrust SAN",
  138:"GoGetSSL EV Code Signing",
  139:"GoGetSSL Multi-Domain Wildcard SSL",
  144:"GoGetSSL Public IP SAN",
  173:"DigiCert Basic OV",
  174:"DigiCert Wildcard SSL",
  175:"DigiCert Basic EV SSL",
  180:"DigiCert Multi-Domain SSL",
  182:"DigiCert EV Multi-Domain",
  185:"GoGetSSL Secure Domain SSL",
  300:"Sectigo ACME Certificate-as-a-Service",
  400:"RapidSSL Plan + Automate",
  401:"RapidSSL Wildcard Plan + Automate",
  402:"GeoTrust DV Plan + Automate",
  403:"GeoTrust DV Wildcard Plan + Automate",
}

export function resolveProductName(o) {
  const r = o?.api_response
  if (!r) return o?.product_name || '—'
  if (r.product_name) return r.product_name
  return PRODUCT_MAP[r.product_id] || o?.product_name || (r.product_id ? `Product #${r.product_id}` : '—')
}

export function resolveCAName(o) {
  return o?.api_response?.ca_name || o?.ca || 'GoGetSSL'
}
